#!/usr/bin/env bash
# Environment Template Generation

source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

# OpenCode config directory
if [[ -z "${OPENCODE_CONFIG_DIR:-}" ]]; then
    readonly OPENCODE_CONFIG_DIR="${HOME}/.config/opencode"
    readonly ENV_FILE="${OPENCODE_CONFIG_DIR}/.env"
    readonly ENV_EXAMPLE_FILE="${OPENCODE_CONFIG_DIR}/.env.example"
fi

generate_env_example() {
    local searxng_port="${1:-8080}"
    local install_github="${2:-false}"
    local install_postgres="${3:-false}"
    local install_sqlite="${4:-false}"
    local install_docker="${5:-false}"
    local install_k8s="${6:-false}"
    
    log_step "Generating environment template..."
    
    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        log_info "$(dry_run_prefix)Would generate $ENV_EXAMPLE_FILE"
        return 0
    fi
    
    mkdir -p "$OPENCODE_CONFIG_DIR"
    
    cat > "$ENV_EXAMPLE_FILE" << EOF
# ===========================================
# OpenCode MCP Environment Variables
# Generated by setup-mcp on $(date)
# Copy to .env and fill in your values
# ===========================================

# === MANDATORY ===
# Engram persistent memory database
ENGRAM_DB_PATH=~/.engram/engram.db

# Codebase memory graph database
CODEBASE_MEMORY_DB=~/.codebase-memory/graph.db

# SearXNG meta search instance
SEARXNG_INSTANCES=http://localhost:${searxng_port}
SEARXNG_USER_AGENT=MCP-SearXNG/1.0

# === OPTIONAL - Set based on installed MCP servers ===
EOF

    if [[ "$install_github" == "true" ]]; then
        cat >> "$ENV_EXAMPLE_FILE" << 'EOF'

# GitHub API access (required for @missionsquad/mcp-github)
# Create token at: https://github.com/settings/tokens
# Required scopes: repo, read:org, read:user
GITHUB_PERSONAL_ACCESS_TOKEN=ghp_xxxx
EOF
    fi

    if [[ "$install_postgres" == "true" ]]; then
        cat >> "$ENV_EXAMPLE_FILE" << 'EOF'

# PostgreSQL connection (required for mcp-postgres)
# Format: postgresql://user:password@host:port/database
POSTGRES_URL=postgresql://user:pass@localhost:5432/mydb
EOF
    fi

    if [[ "$install_sqlite" == "true" ]]; then
        cat >> "$ENV_EXAMPLE_FILE" << 'EOF'

# SQLite - no additional config needed (uses local files)
EOF
    fi

    if [[ "$install_docker" == "true" ]]; then
        cat >> "$ENV_EXAMPLE_FILE" << 'EOF'

# Docker - uses local docker.sock, no config needed
EOF
    fi

    if [[ "$install_k8s" == "true" ]]; then
        cat >> "$ENV_EXAMPLE_FILE" << 'EOF'

# Kubernetes - uses ~/.kube/config, no config needed
EOF
    fi

    cat >> "$ENV_EXAMPLE_FILE" << 'EOF'

# === AI MODEL CONFIGURATION ===
# NVIDIA NIM API Key (for cloud models)
# Get from: https://build.nvidia.com/
NVIDIA_API_KEY=nvapi_xxxx

# Ollama local models
# Default: http://localhost:11434
OLLAMA_HOST=http://localhost:11434

# === ADVANCED ===
# NODE_TLS_REJECT_UNAUTHORIZED=0  # Disable SSL verify (dev only)
EOF

    log_success "Environment template generated: $ENV_EXAMPLE_FILE"
    
    # Also create .env if it doesn't exist
    if [[ ! -f "$ENV_FILE" ]]; then
        cp "$ENV_EXAMPLE_FILE" "$ENV_FILE"
        log_info "Created .env from template (edit with your values)"
    fi
}

# Validate required environment variables
validate_env() {
    local missing=()
    
    # Check mandatory
    if [[ -z "${ENGRAM_DB_PATH:-}" ]]; then
        missing+=("ENGRAM_DB_PATH")
    fi
    
    if [[ -z "${CODEBASE_MEMORY_DB:-}" ]]; then
        missing+=("CODEBASE_MEMORY_DB")
    fi
    
    if [[ -z "${SEARXNG_INSTANCES:-}" ]]; then
        missing+=("SEARXNG_INSTANCES")
    fi
    
    if [[ ${#missing[@]} -gt 0 ]]; then
        log_warn "Missing environment variables: ${missing[*]}"
        log_info "Run: source $ENV_FILE (after editing)"
        return 1
    fi
    
    log_success "All mandatory environment variables set"
    return 0
}

# Load environment file
load_env() {
    if [[ -f "$ENV_FILE" ]]; then
        # shellcheck source=/dev/null
        set -a
        source "$ENV_FILE"
        set +a
        log_debug "Loaded environment from $ENV_FILE"
    elif [[ -f "$ENV_EXAMPLE_FILE" ]]; then
        log_warn ".env not found, using .env.example"
        # shellcheck source=/dev/null
        set -a
        source "$ENV_EXAMPLE_FILE"
        set +a
    else
        log_warn "No environment file found"
    fi
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    generate_env_example 8080 true true true true true
fi