#!/usr/bin/env bash
# SearXNG Docker Installation and Health Check using docker-compose

source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

# SearXNG configuration
if [[ -z "${SEARXNG_IMAGE:-}" ]]; then
    readonly SEARXNG_IMAGE="searxng/searxng"
    readonly SEARXNG_CONTAINER_NAME="searxng"
    readonly SEARXNG_BASE_PORT=1012
    readonly SEARXNG_CONFIG_DIR="${HOME}/.config/searxng"
    readonly SEARXNG_HEALTH_ENDPOINT="/search?q=test&format=json"
    readonly SEARXNG_HEALTH_TIMEOUT=120
    readonly SEARXNG_COMPOSE_DIR="${HOME}/.config/searxng"
    readonly SEARXNG_COMPOSE_FILE="${SEARXNG_COMPOSE_DIR}/docker-compose.yml"
    readonly SEARXNG_ENV_FILE="${SEARXNG_COMPOSE_DIR}/.env"
fi

install_searxng() {
    log_step "Installing SearXNG with docker-compose..."
    
    # Create config directory and docker-compose.yml
    create_searxng_compose
    create_searxng_config
    create_searxng_env
    
    # Find free port (use 1012 as base)
    local port
    port=$(find_free_port "$SEARXNG_BASE_PORT")
    
    if [[ -z "$port" ]]; then
        log_error "Could not find free port for SearXNG"
        return 1
    fi
    
    log_info "Using port $port for SearXNG"
    
    # Update .env with the selected port
    if [[ "${DRY_RUN:-false}" != "true" ]]; then
        sed -i "s/^SEARXNG_PORT=.*/SEARXNG_PORT=$port/" "$SEARXNG_ENV_FILE"
    fi
    
    # Pull images
    pull_searxng_images
    
    # Stop existing compose if exists
    stop_existing_searxng
    
    # Run docker-compose
    run_searxng_compose
    
    # Health check
    if wait_for_searxng_health "$port"; then
        log_success "SearXNG is running on port $port"
        export SEARXNG_PORT="$port"
        export SEARXNG_INSTANCES="http://localhost:$port"
        return 0
    else
        log_error "SearXNG health check failed"
        return 1
    fi
}

create_searxng_compose() {
    log_substep "Creating docker-compose.yml for SearXNG..."
    
    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        log_info "$(dry_run_prefix)Would create $SEARXNG_COMPOSE_FILE"
        return 0
    fi
    
    mkdir -p "$SEARXNG_COMPOSE_DIR"
    
    cat > "$SEARXNG_COMPOSE_FILE" << 'EOF'
# SearXNG with Valkey (Redis-compatible) - Docker Compose
# Based on https://docs.searxng.org/admin/installation-docker.html
# Generated by setup-mcp script

services:
  core:
    container_name: searxng-core
    image: docker.io/searxng/searxng:${SEARXNG_VERSION:-latest}
    restart: always
    ports:
      - "${SEARXNG_HOST:+${SEARXNG_HOST}:}${SEARXNG_PORT:-1012}:${SEARXNG_PORT:-8080}"
    env_file: .env
    volumes:
      - ./core-config/:/etc/searxng/:Z
      - core-data:/var/cache/searxng/
    depends_on:
      valkey:
        condition: service_healthy

  valkey:
    container_name: searxng-valkey
    image: docker.io/valkey/valkey:9-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: always
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - valkey-data:/data/

volumes:
  core-data:
  valkey-data:
EOF
    
    log_success "docker-compose.yml created at $SEARXNG_COMPOSE_FILE"
}

create_searxng_config() {
    log_substep "Creating SearXNG configuration..."
    
    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        log_info "$(dry_run_prefix)Would create $SEARXNG_CONFIG_DIR/settings.yml"
        return 0
    fi
    
    mkdir -p "$SEARXNG_COMPOSE_DIR/core-config"
    
    cat > "$SEARXNG_COMPOSE_DIR/core-config/settings.yml" << 'EOF'
# SearXNG Configuration - Basic Setup
# Generated by setup-mcp script

general:
  debug: false
  instance_name: "SearXNG MCP"
  contact_url: false
  enable_metrics: false

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "changeme"
  limiter: false
  image_proxy: true

ui:
  static_use_hash: true
  default_theme: simple
  default_locale: ""
  center_alignment: false

search:
  safe_search: 1
  autocomplete: ""
  default_lang: "all"
  formats:
    - html
    - json
  categories:
    - general
  language_cookies_expire: 30

engines:
  - name: google
    engine: google
    shortcut: g
    tokens: [google]
    disabled: false
  - name: duckduckgo
    engine: duckduckgo
    shortcut: d
    tokens: [duckduckgo]
    disabled: false
  - name: bing
    engine: bing
    shortcut: b
    tokens: [bing]
    disabled: false

redis:
  enabled: true
  host: valkey
  port: 6379

database:
  enabled: false
EOF
    
    log_success "SearXNG config created at $SEARXNG_COMPOSE_DIR/core-config/settings.yml"
}

create_searxng_env() {
    log_substep "Creating .env file for SearXNG..."
    
    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        log_info "$(dry_run_prefix)Would create $SEARXNG_ENV_FILE"
        return 0
    fi
    
    cat > "$SEARXNG_ENV_FILE" << 'EOF'
# SearXNG Environment Variables
# Generated by setup-mcp script

# General
SEARXNG_VERSION=latest
SEARXNG_HOST=
SEARXNG_PORT=1012

# Redis/Valkey
REDIS_HOST=valkey
REDIS_PORT=6379

# SearXNG Settings
SEARXNG_SECRET_KEY=changeme
SEARXNG_LIMITER=false
SEARXNG_IMAGE_PROXY=true
SEARXNG_SAFE_SEARCH=1
SEARXNG_DEFAULT_LANG=all
EOF
    
    log_success ".env file created at $SEARXNG_ENV_FILE"
}

pull_searxng_images() {
    log_substep "Pulling SearXNG and Valkey Docker images..."
    
    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        log_info "$(dry_run_prefix)Would run: docker compose -f $SEARXNG_COMPOSE_FILE pull"
        return 0
    fi
    
    run_cmd "docker_cmd compose -f $SEARXNG_COMPOSE_FILE pull" "Pull SearXNG and Valkey images"
}

stop_existing_searxng() {
    log_substep "Stopping existing SearXNG containers..."
    
    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        log_info "$(dry_run_prefix)Would run: docker compose -f $SEARXNG_COMPOSE_FILE down"
        return 0
    fi
    
    run_cmd "docker_cmd compose -f $SEARXNG_COMPOSE_FILE down -v" "Stop and remove existing SearXNG containers"
}

run_searxng_compose() {
    log_substep "Starting SearXNG with docker-compose..."
    
    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        log_info "$(dry_run_prefix)Would run: docker compose -f $SEARXNG_COMPOSE_FILE up -d"
        return 0
    fi
    
    run_cmd "docker_cmd compose -f $SEARXNG_COMPOSE_FILE up -d" "Start SearXNG with docker-compose"
}

wait_for_searxng_health() {
    local port="$1"
    local url="http://localhost:$port/search?q=test&format=json"
    
    log_substep "Waiting for SearXNG to be healthy on port $port..."
    
    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        log_info "$(dry_run_prefix)Would wait for health check at $url"
        return 0
    fi
    
    local attempt=1
    local max_attempts=$((SEARXNG_HEALTH_TIMEOUT / 2))
    
    while [[ $attempt -le $max_attempts ]]; do
        if curl -sf "http://localhost:$port/search?q=test&format=json" >/dev/null 2>&1; then
            log_success "SearXNG is healthy and responding"
            return 0
        fi
        
        if [[ $((attempt % 5)) -eq 0 ]]; then
            log_substep "Health check attempt $attempt/$max_attempts..."
        fi
        
        sleep 2
        attempt=$((attempt + 1))
    done
    
    # Show container logs for debugging
    log_error "SearXNG health check failed after ${SEARXNG_HEALTH_TIMEOUT}s"
    log_substep "Container logs:"
    docker_cmd compose -f "$SEARXNG_COMPOSE_FILE" logs --tail 50 2>/dev/null || true
    
    return 1
}

# Get SearXNG status
searxng_status() {
    if docker_cmd compose -f "$SEARXNG_COMPOSE_FILE" ps --format '{{.Names}}' | grep -q "^searxng-core$"; then
        local port
        port=$(docker_cmd port searxng-core 2>/dev/null | grep '8080/tcp' | cut -d: -f2 | head -1)
        echo "running:$port"
    else
        echo "stopped"
    fi
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    install_searxng
fi