#!/usr/bin/env bash
# SearXNG Docker Installation and Health Check

source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

# SearXNG configuration
if [[ -z "${SEARXNG_IMAGE:-}" ]]; then
    readonly SEARXNG_IMAGE="searxng/searxng"
    readonly SEARXNG_CONTAINER_NAME="searxng"
    readonly SEARXNG_BASE_PORT=8080
    readonly SEARXNG_CONFIG_DIR="${HOME}/.config/searxng"
    readonly SEARXNG_HEALTH_ENDPOINT="/search?q=test&format=json"
    readonly SEARXNG_HEALTH_TIMEOUT=60
fi

install_searxng() {
    log_step "Installing SearXNG..."
    
    # Create config directory and settings.yml
    create_searxng_config
    
    # Find free port
    local port
    port=$(find_free_port "$SEARXNG_BASE_PORT")
    
    if [[ -z "$port" ]]; then
        log_error "Could not find free port for SearXNG"
        return 1
    fi
    
    log_info "Using port $port for SearXNG"
    
    # Pull image
    pull_searxng_image
    
    # Stop existing container if using same port
    stop_existing_searxng "$port"
    
    # Run container
    run_searxng_container "$port"
    
    # Health check
    if wait_for_searxng_health "$port"; then
        log_success "SearXNG is running on port $port"
        export SEARXNG_PORT="$port"
        export SEARXNG_INSTANCES="http://localhost:$port"
        return 0
    else
        log_error "SearXNG health check failed"
        return 1
    fi
}

create_searxng_config() {
    log_substep "Creating SearXNG configuration..."
    
    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        log_info "$(dry_run_prefix)Would create $SEARXNG_CONFIG_DIR/settings.yml"
        return 0
    fi
    
    mkdir -p "$SEARXNG_CONFIG_DIR"
    
    cat > "$SEARXNG_CONFIG_DIR/settings.yml" << 'EOF'
# SearXNG Configuration - Basic Setup
# Generated by setup-mcp script

general:
  debug: false
  instance_name: "SearXNG MCP"
  contact_url: false
  enable_metrics: false

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "changeme"
  limiter: false
  image_proxy: true

ui:
  static_use_hash: true
  default_theme: simple
  default_locale: ""
  center_alignment: false

search:
  safe_search: 1
  autocomplete: ""
  default_lang: "all"
  formats:
    - html
    - json
  categories:
    - general
  language_cookies_expire: 30

engines:
  - name: google
    engine: google
    shortcut: g
    tokens: [google]
    disabled: false
  - name: duckduckgo
    engine: duckduckgo
    shortcut: d
    tokens: [duckduckgo]
    disabled: false
  - name: bing
    engine: bing
    shortcut: b
    tokens: [bing]
    disabled: false

redis:
  enabled: false

database:
  enabled: false
EOF
    
    log_success "SearXNG config created at $SEARXNG_CONFIG_DIR/settings.yml"
}

pull_searxng_image() {
    log_substep "Pulling SearXNG Docker image..."
    
    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        log_info "$(dry_run_prefix)Would run: docker pull $SEARXNG_IMAGE"
        return 0
    fi
    
    run_cmd "docker_cmd pull $SEARXNG_IMAGE" "Pull SearXNG image"
}

stop_existing_searxng() {
    local port="$1"
    
    # Check if container with same name exists
    if docker_cmd ps -a --format '{{.Names}}' | grep -q "^${SEARXNG_CONTAINER_NAME}$"; then
        log_substep "Stopping existing SearXNG container..."
        run_cmd "docker_cmd stop $SEARXNG_CONTAINER_NAME" "Stop existing container"
        run_cmd "docker_cmd rm $SEARXNG_CONTAINER_NAME" "Remove existing container"
    fi
    
    # Check if any container is using our target port
    local container_id
    container_id=$(docker_cmd ps --filter "publish=$port" --format '{{.ID}}' | head -1)
    
    if [[ -n "$container_id" ]]; then
        log_warn "Port $port in use by container $container_id, stopping..."
        run_cmd "docker_cmd stop $container_id" "Stop container on port $port"
    fi
}

run_searxng_container() {
    local port="$1"
    
    log_substep "Starting SearXNG container on port $port..."
    
    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        log_info "$(dry_run_prefix)Would run: docker run -d --name $SEARXNG_CONTAINER_NAME --restart always -p $port:8080 -v $SEARXNG_CONFIG_DIR:/etc/searxng $SEARXNG_IMAGE"
        return 0
    fi
    
    run_cmd "docker_cmd run -d \
        --name $SEARXNG_CONTAINER_NAME \
        --restart always \
        -p $port:8080 \
        -v $SEARXNG_CONFIG_DIR:/etc/searxng \
        $SEARXNG_IMAGE" "Start SearXNG container"
}

wait_for_searxng_health() {
    local port="$1"
    local url="http://localhost:$port$SEARXNG_HEALTH_ENDPOINT"
    
    log_substep "Waiting for SearXNG to be healthy on port $port..."
    
    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        log_info "$(dry_run_prefix)Would wait for health check at $url"
        return 0
    fi
    
    local attempt=1
    local max_attempts=$((SEARXNG_HEALTH_TIMEOUT / 2))
    
    while [[ $attempt -le $max_attempts ]]; do
        if curl -sf "$url" >/dev/null 2>&1; then
            log_success "SearXNG is healthy and responding"
            return 0
        fi
        
        if [[ $((attempt % 5)) -eq 0 ]]; then
            log_substep "Health check attempt $attempt/$max_attempts..."
        fi
        
        sleep 2
        attempt=$((attempt + 1))
    done
    
    # Show container logs for debugging
    log_error "SearXNG health check failed after ${SEARXNG_HEALTH_TIMEOUT}s"
    log_substep "Container logs:"
    docker_cmd logs "$SEARXNG_CONTAINER_NAME" --tail 50 2>/dev/null || true
    
    return 1
}

# Get SearXNG status
searxng_status() {
    if docker_cmd ps --format '{{.Names}}' | grep -q "^${SEARXNG_CONTAINER_NAME}$"; then
        local port
        port=$(docker_cmd port "$SEARXNG_CONTAINER_NAME" 2>/dev/null | grep '8080/tcp' | cut -d: -f2 | head -1)
        echo "running:$port"
    else
        echo "stopped"
    fi
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    install_searxng
fi